import type { ComponentDefinition } from '@/types'

const defaultSize = { value: 1, unit: 'auto' as const }

export const componentDefinitions: ComponentDefinition[] = [
  // ── Layout ────────────────────────────────────────────
  {
    type: 'Container',
    displayName: 'Container',
    category: 'layout',
    icon: 'box',
    htmlTag: 'div',
    isContainer: true,
    allowedChildren: true,
    allowedParents: null,
    defaultProps: {},
    defaultStyles: {
      width: { value: 400, unit: 'px' },
      height: { value: 300, unit: 'px' },
      backgroundColor: '#f0f0f0',
      borderRadius: { value: 8, unit: 'px' },
      padding: { top: { value: 16, unit: 'px' }, right: { value: 16, unit: 'px' }, bottom: { value: 16, unit: 'px' }, left: { value: 16, unit: 'px' } },
      position: 'absolute',
      x: { value: 0, unit: 'px' },
      y: { value: 0, unit: 'px' },
      overflow: 'visible',
    },
    properties: [
      { name: 'width', label: 'Width', type: 'size', defaultValue: { value: 400, unit: 'px' } },
      { name: 'height', label: 'Height', type: 'size', defaultValue: { value: 300, unit: 'px' } },
      { name: 'backgroundColor', label: 'Background', type: 'color', defaultValue: '#f0f0f0' },
      { name: 'borderRadius', label: 'Border Radius', type: 'size', defaultValue: { value: 8, unit: 'px' } },
      { name: 'opacity', label: 'Opacity', type: 'number', defaultValue: 1, validation: { min: 0, max: 1 } },
    ],
  },
  {
    type: 'FlexContainer',
    displayName: 'Flex Container',
    category: 'layout',
    icon: 'columns',
    htmlTag: 'div',
    isContainer: true,
    allowedChildren: true,
    allowedParents: null,
    defaultProps: {
      flexDirection: 'row',
      justifyContent: 'flex-start',
      alignItems: 'stretch',
      gap: 8,
    },
    defaultStyles: {
      display: 'flex',
      width: { value: 400, unit: 'px' },
      height: { value: 200, unit: 'px' },
      backgroundColor: '#e8f0fe',
      padding: { top: { value: 16, unit: 'px' }, right: { value: 16, unit: 'px' }, bottom: { value: 16, unit: 'px' }, left: { value: 16, unit: 'px' } },
      borderRadius: { value: 8, unit: 'px' },
      position: 'absolute',
      x: { value: 0, unit: 'px' },
      y: { value: 0, unit: 'px' },
      overflow: 'visible',
    },
    properties: [
      { name: 'flexDirection', label: 'Direction', type: 'select', defaultValue: 'row', options: [
        { label: 'Row', value: 'row' }, { label: 'Column', value: 'column' },
        { label: 'Row Reverse', value: 'row-reverse' }, { label: 'Column Reverse', value: 'column-reverse' },
      ]},
      { name: 'justifyContent', label: 'Justify', type: 'select', defaultValue: 'flex-start', options: [
        { label: 'Start', value: 'flex-start' }, { label: 'End', value: 'flex-end' },
        { label: 'Center', value: 'center' }, { label: 'Space Between', value: 'space-between' },
        { label: 'Space Around', value: 'space-around' }, { label: 'Space Evenly', value: 'space-evenly' },
      ]},
      { name: 'alignItems', label: 'Align', type: 'select', defaultValue: 'stretch', options: [
        { label: 'Start', value: 'flex-start' }, { label: 'End', value: 'flex-end' },
        { label: 'Center', value: 'center' }, { label: 'Stretch', value: 'stretch' }, { label: 'Baseline', value: 'baseline' },
      ]},
      { name: 'gap', label: 'Gap', type: 'size', defaultValue: { value: 8, unit: 'px' } },
    ],
  },
  {
    type: 'GridContainer',
    displayName: 'Grid Container',
    category: 'layout',
    icon: 'grid3x3',
    htmlTag: 'div',
    isContainer: true,
    allowedChildren: true,
    allowedParents: null,
    defaultProps: {
      gridTemplateColumns: '1fr 1fr 1fr',
      gridTemplateRows: 'auto',
      gap: 8,
    },
    defaultStyles: {
      display: 'grid',
      width: { value: 400, unit: 'px' },
      height: { value: 200, unit: 'px' },
      backgroundColor: '#fef3e8',
      padding: { top: { value: 16, unit: 'px' }, right: { value: 16, unit: 'px' }, bottom: { value: 16, unit: 'px' }, left: { value: 16, unit: 'px' } },
      borderRadius: { value: 8, unit: 'px' },
      position: 'absolute',
      x: { value: 0, unit: 'px' },
      y: { value: 0, unit: 'px' },
      overflow: 'visible',
    },
    properties: [
      { name: 'gridTemplateColumns', label: 'Columns', type: 'string', defaultValue: '1fr 1fr 1fr' },
      { name: 'gridTemplateRows', label: 'Rows', type: 'string', defaultValue: 'auto' },
      { name: 'gap', label: 'Gap', type: 'size', defaultValue: { value: 8, unit: 'px' } },
    ],
  },

  // ── Forms ──────────────────────────────────────────────
  {
    type: 'Button',
    displayName: 'Button',
    category: 'forms',
    icon: 'rectangle-ellipsis',
    htmlTag: 'button',
    isContainer: false,
    allowedChildren: false,
    allowedParents: null,
    defaultProps: { text: 'Button', variant: 'primary', disabled: false },
    defaultStyles: {
      width: { value: 120, unit: 'px' },
      height: { value: 40, unit: 'px' },
      backgroundColor: '#3b82f6',
      color: '#ffffff',
      borderRadius: { value: 6, unit: 'px' },
      fontSize: { value: 14, unit: 'px' },
      fontWeight: 600,
      position: 'absolute',
      x: { value: 0, unit: 'px' },
      y: { value: 0, unit: 'px' },
      cursor: 'pointer',
      borderStyle: 'none',
      display: 'inline-block',
      textAlign: 'center',
    },
    properties: [
      { name: 'text', label: 'Text', type: 'string', defaultValue: 'Button' },
      { name: 'backgroundColor', label: 'Background', type: 'color', defaultValue: '#3b82f6' },
      { name: 'color', label: 'Text Color', type: 'color', defaultValue: '#ffffff' },
      { name: 'borderRadius', label: 'Border Radius', type: 'size', defaultValue: { value: 6, unit: 'px' } },
      { name: 'disabled', label: 'Disabled', type: 'boolean', defaultValue: false },
    ],
  },
  {
    type: 'Input',
    displayName: 'Input',
    category: 'forms',
    icon: 'type',
    htmlTag: 'input',
    isContainer: false,
    allowedChildren: false,
    allowedParents: null,
    defaultProps: { placeholder: 'Enter text...', value: '', type: 'text' },
    defaultStyles: {
      width: { value: 200, unit: 'px' },
      height: { value: 36, unit: 'px' },
      backgroundColor: '#ffffff',
      color: '#333333',
      borderWidth: { value: 1, unit: 'px' },
      borderColor: '#d1d5db',
      borderStyle: 'solid',
      borderRadius: { value: 6, unit: 'px' },
      fontSize: { value: 14, unit: 'px' },
      padding: { top: { value: 8, unit: 'px' }, right: { value: 12, unit: 'px' }, bottom: { value: 8, unit: 'px' }, left: { value: 12, unit: 'px' } },
      position: 'absolute',
      x: { value: 0, unit: 'px' },
      y: { value: 0, unit: 'px' },
      display: 'inline-block',
    },
    properties: [
      { name: 'placeholder', label: 'Placeholder', type: 'string', defaultValue: 'Enter text...' },
      { name: 'value', label: 'Value', type: 'string', defaultValue: '' },
      { name: 'type', label: 'Type', type: 'select', defaultValue: 'text', options: [
        { label: 'Text', value: 'text' }, { label: 'Password', value: 'password' },
        { label: 'Email', value: 'email' }, { label: 'Number', value: 'number' },
      ]},
      { name: 'backgroundColor', label: 'Background', type: 'color', defaultValue: '#ffffff' },
    ],
  },
  {
    type: 'TextArea',
    displayName: 'Text Area',
    category: 'forms',
    icon: 'align-left',
    htmlTag: 'textarea',
    isContainer: false,
    allowedChildren: false,
    allowedParents: null,
    defaultProps: { placeholder: 'Enter text...', value: '' },
    defaultStyles: {
      width: { value: 300, unit: 'px' },
      height: { value: 100, unit: 'px' },
      backgroundColor: '#ffffff',
      color: '#333333',
      borderWidth: { value: 1, unit: 'px' },
      borderColor: '#d1d5db',
      borderStyle: 'solid',
      borderRadius: { value: 6, unit: 'px' },
      fontSize: { value: 14, unit: 'px' },
      padding: { top: { value: 8, unit: 'px' }, right: { value: 12, unit: 'px' }, bottom: { value: 8, unit: 'px' }, left: { value: 12, unit: 'px' } },
      position: 'absolute',
      x: { value: 0, unit: 'px' },
      y: { value: 0, unit: 'px' },
      display: 'inline-block',
      overflow: 'auto',
    },
    properties: [
      { name: 'placeholder', label: 'Placeholder', type: 'string', defaultValue: 'Enter text...' },
      { name: 'value', label: 'Value', type: 'textarea', defaultValue: '' },
      { name: 'backgroundColor', label: 'Background', type: 'color', defaultValue: '#ffffff' },
    ],
  },
  {
    type: 'Checkbox',
    displayName: 'Checkbox',
    category: 'forms',
    icon: 'check-square',
    htmlTag: 'input',
    isContainer: false,
    allowedChildren: false,
    allowedParents: null,
    defaultProps: { label: 'Checkbox', checked: false },
    defaultStyles: {
      width: { value: 18, unit: 'px' },
      height: { value: 18, unit: 'px' },
      position: 'absolute',
      x: { value: 0, unit: 'px' },
      y: { value: 0, unit: 'px' },
      cursor: 'pointer',
    },
    properties: [
      { name: 'label', label: 'Label', type: 'string', defaultValue: 'Checkbox' },
      { name: 'checked', label: 'Checked', type: 'boolean', defaultValue: false },
    ],
  },
  {
    type: 'Select',
    displayName: 'Select',
    category: 'forms',
    icon: 'chevron-down',
    htmlTag: 'select',
    isContainer: false,
    allowedChildren: false,
    allowedParents: null,
    defaultProps: { options: 'Option 1,Option 2,Option 3' },
    defaultStyles: {
      width: { value: 200, unit: 'px' },
      height: { value: 36, unit: 'px' },
      backgroundColor: '#ffffff',
      color: '#333333',
      borderWidth: { value: 1, unit: 'px' },
      borderColor: '#d1d5db',
      borderStyle: 'solid',
      borderRadius: { value: 6, unit: 'px' },
      fontSize: { value: 14, unit: 'px' },
      padding: { top: { value: 8, unit: 'px' }, right: { value: 12, unit: 'px' }, bottom: { value: 8, unit: 'px' }, left: { value: 12, unit: 'px' } },
      position: 'absolute',
      x: { value: 0, unit: 'px' },
      y: { value: 0, unit: 'px' },
      display: 'inline-block',
    },
    properties: [
      { name: 'options', label: 'Options (comma-separated)', type: 'string', defaultValue: 'Option 1,Option 2,Option 3' },
      { name: 'backgroundColor', label: 'Background', type: 'color', defaultValue: '#ffffff' },
    ],
  },
  {
    type: 'Label',
    displayName: 'Label',
    category: 'forms',
    icon: 'text',
    htmlTag: 'label',
    isContainer: false,
    allowedChildren: false,
    allowedParents: null,
    defaultProps: { text: 'Label', htmlFor: '' },
    defaultStyles: {
      fontSize: { value: 14, unit: 'px' },
      fontWeight: 500,
      color: '#374151',
      position: 'absolute',
      x: { value: 0, unit: 'px' },
      y: { value: 0, unit: 'px' },
      display: 'inline-block',
    },
    properties: [
      { name: 'text', label: 'Text', type: 'string', defaultValue: 'Label' },
      { name: 'htmlFor', label: 'For (input ID)', type: 'string', defaultValue: '' },
      { name: 'color', label: 'Color', type: 'color', defaultValue: '#374151' },
      { name: 'fontSize', label: 'Font Size', type: 'size', defaultValue: { value: 14, unit: 'px' } },
      { name: 'fontWeight', label: 'Font Weight', type: 'select', defaultValue: 500, options: [
        { label: 'Normal', value: '400' }, { label: 'Medium', value: '500' },
        { label: 'Semibold', value: '600' }, { label: 'Bold', value: '700' },
      ]},
    ],
  },

  // ── Content ────────────────────────────────────────────
  {
    type: 'Text',
    displayName: 'Text',
    category: 'content',
    icon: 'type',
    htmlTag: 'span',
    isContainer: false,
    allowedChildren: false,
    allowedParents: null,
    defaultProps: { text: 'Hello World' },
    defaultStyles: {
      fontSize: { value: 14, unit: 'px' },
      color: '#111827',
      fontFamily: 'system-ui, sans-serif',
      position: 'absolute',
      x: { value: 0, unit: 'px' },
      y: { value: 0, unit: 'px' },
      display: 'inline-block',
    },
    properties: [
      { name: 'text', label: 'Text', type: 'string', defaultValue: 'Hello World' },
      { name: 'fontSize', label: 'Font Size', type: 'size', defaultValue: { value: 14, unit: 'px' } },
      { name: 'color', label: 'Color', type: 'color', defaultValue: '#111827' },
      { name: 'fontFamily', label: 'Font', type: 'string', defaultValue: 'system-ui, sans-serif' },
      { name: 'fontWeight', label: 'Weight', type: 'select', defaultValue: 400, options: [
        { label: 'Normal', value: '400' }, { label: 'Medium', value: '500' },
        { label: 'Semibold', value: '600' }, { label: 'Bold', value: '700' },
      ]},
    ],
  },
  {
    type: 'Heading',
    displayName: 'Heading',
    category: 'content',
    icon: 'heading',
    htmlTag: 'h2',
    isContainer: false,
    allowedChildren: false,
    allowedParents: null,
    defaultProps: { text: 'Heading', level: 'h2' },
    defaultStyles: {
      fontSize: { value: 24, unit: 'px' },
      fontWeight: 700,
      color: '#111827',
      fontFamily: 'system-ui, sans-serif',
      position: 'absolute',
      x: { value: 0, unit: 'px' },
      y: { value: 0, unit: 'px' },
      display: 'block',
    },
    properties: [
      { name: 'text', label: 'Text', type: 'string', defaultValue: 'Heading' },
      { name: 'level', label: 'Level', type: 'select', defaultValue: 'h2', options: [
        { label: 'H1', value: 'h1' }, { label: 'H2', value: 'h2' },
        { label: 'H3', value: 'h3' }, { label: 'H4', value: 'h4' },
      ]},
      { name: 'fontSize', label: 'Font Size', type: 'size', defaultValue: { value: 24, unit: 'px' } },
      { name: 'color', label: 'Color', type: 'color', defaultValue: '#111827' },
    ],
  },
  {
    type: 'Image',
    displayName: 'Image',
    category: 'media',
    icon: 'image',
    htmlTag: 'img',
    isContainer: false,
    allowedChildren: false,
    allowedParents: null,
    selfClosing: true,
    defaultProps: { src: '', alt: 'Image', objectFit: 'cover' },
    defaultStyles: {
      width: { value: 200, unit: 'px' },
      height: { value: 160, unit: 'px' },
      backgroundColor: '#e5e7eb',
      borderRadius: { value: 4, unit: 'px' },
      position: 'absolute',
      x: { value: 0, unit: 'px' },
      y: { value: 0, unit: 'px' },
      overflow: 'hidden',
    },
    properties: [
      { name: 'src', label: 'Source URL', type: 'string', defaultValue: '' },
      { name: 'alt', label: 'Alt Text', type: 'string', defaultValue: 'Image' },
      { name: 'objectFit', label: 'Fit', type: 'select', defaultValue: 'cover', options: [
        { label: 'Cover', value: 'cover' }, { label: 'Contain', value: 'contain' },
        { label: 'Fill', value: 'fill' }, { label: 'None', value: 'none' },
      ]},
    ],
  },
]

export const registry = new Map<string, ComponentDefinition>()
componentDefinitions.forEach(def => registry.set(def.type, def))

export function getComponentDefinition(type: string): ComponentDefinition | undefined {
  return registry.get(type)
}

export function getComponentsByCategory(): Record<string, ComponentDefinition[]> {
  const grouped: Record<string, ComponentDefinition[]> = {}
  componentDefinitions.forEach(def => {
    if (!grouped[def.category]) grouped[def.category] = []
    grouped[def.category].push(def)
  })
  return grouped
}
